/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gelismisform;

/**
 *
 * @author ASUS PC
 */
public class BilgiFormu extends javax.swing.JFrame {
    public String isim,soyIsim,yas,cinsiyet,medeniHal;

    public String getIsim() {
        return isim;
    }

    public void setIsim(String isim) {
        this.isim = isim;
    }

    public String getSoyIsim() {
        return soyIsim;
    }

    public void setSoyIsim(String soyIsim) {
        this.soyIsim = soyIsim;
    }

    public String getYas() {
        return yas;
    }

    public void setYas(String yas) {
        this.yas = yas;
    }

    public String getCinsiyet() {
        return cinsiyet;
    }

    public void setCinsiyet(String cinsiyet) {
        this.cinsiyet = cinsiyet;
    }

    public String getMedeniHal() {
        return medeniHal;
    }

    public void setMedeniHal(String medeniHal) {
        this.medeniHal = medeniHal;
    }
    
    public BilgiFormu(String isim,String soyIsim,String yas,String cinsiyet,String medeniHal){
        initComponents();
        this.isim=isim;
        this.soyIsim=soyIsim;
        this.yas=yas;
        this.cinsiyet=cinsiyet;
        this.medeniHal=medeniHal;
    }

    BilgiFormu() {
       initComponents();

    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kisiselBilgiLbl = new javax.swing.JLabel();
        egitimLbl = new javax.swing.JLabel();
        mezuniyetDereceBilgiLbl = new javax.swing.JLabel();
        mezuniyetOkulBilgiLbl = new javax.swing.JLabel();
        mezOrtBilgi = new javax.swing.JLabel();
        iletisimBilgileriLbl = new javax.swing.JLabel();
        telNoLbl = new javax.swing.JLabel();
        epostaLbl = new javax.swing.JLabel();
        isimBilgiLbl = new javax.swing.JLabel();
        SoyIsimBilgiLbl = new javax.swing.JLabel();
        yasBilgiLbl = new javax.swing.JLabel();
        cinsiyetBilgiLbl = new javax.swing.JLabel();
        medeniHalBilgiLbl = new javax.swing.JLabel();
        bilgiIsimLbl = new javax.swing.JLabel();
        bilgiSoyIsimLbl = new javax.swing.JLabel();
        bilgiYasLbl = new javax.swing.JLabel();
        mezDerBilgi = new javax.swing.JLabel();
        mezOkulBilgi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telBilgi = new javax.swing.JLabel();
        epostaBilgi = new javax.swing.JLabel();
        bilgiCinsiyetLbl = new javax.swing.JLabel();
        bilgiMedeniHalLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kisiselBilgiLbl.setText("Kişisel Bilgiler");

        egitimLbl.setText("Eğitim Bilgileri");

        mezuniyetDereceBilgiLbl.setText("Mezuniyet Derecesi");

        mezuniyetOkulBilgiLbl.setText("Mezun Olunan Okul");

        mezOrtBilgi.setText("Mezuniyet Ortalaması");

        iletisimBilgileriLbl.setText("İletişim Bilgileri");

        telNoLbl.setText("Telefon Numarası");

        epostaLbl.setText("E-posta Adresi");

        isimBilgiLbl.setText("İsim");

        SoyIsimBilgiLbl.setText("Soyisim");

        yasBilgiLbl.setText("Yaş");

        cinsiyetBilgiLbl.setText("Cinsiyet");

        medeniHalBilgiLbl.setText("Medeni Hal");

        bilgiIsimLbl.setBackground(new java.awt.Color(153, 255, 0));
        bilgiIsimLbl.setText("1");

        bilgiSoyIsimLbl.setText("2");

        bilgiYasLbl.setText("3");

        mezDerBilgi.setText("1");

        mezOkulBilgi.setText("2");

        jLabel6.setText("3");

        telBilgi.setText("1");

        epostaBilgi.setText("2");

        bilgiCinsiyetLbl.setText("4");

        bilgiMedeniHalLbl.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(kisiselBilgiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isimBilgiLbl)
                            .addComponent(SoyIsimBilgiLbl)
                            .addComponent(yasBilgiLbl)
                            .addComponent(cinsiyetBilgiLbl)
                            .addComponent(medeniHalBilgiLbl))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bilgiYasLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(bilgiSoyIsimLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(bilgiIsimLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(bilgiCinsiyetLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bilgiMedeniHalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(egitimLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iletisimBilgileriLbl)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mezOrtBilgi)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mezuniyetDereceBilgiLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mezDerBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mezuniyetOkulBilgiLbl)
                                .addGap(18, 18, 18)
                                .addComponent(mezOkulBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telNoLbl)
                            .addComponent(epostaLbl))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(epostaBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kisiselBilgiLbl)
                    .addComponent(egitimLbl)
                    .addComponent(iletisimBilgileriLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isimBilgiLbl)
                    .addComponent(bilgiIsimLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mezuniyetDereceBilgiLbl)
                            .addComponent(mezDerBilgi, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(telNoLbl)
                            .addComponent(telBilgi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mezuniyetOkulBilgiLbl)
                                    .addComponent(mezOkulBilgi)
                                    .addComponent(epostaLbl))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(epostaBilgi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mezOrtBilgi)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medeniHalBilgiLbl)
                            .addComponent(bilgiMedeniHalLbl))
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoyIsimBilgiLbl)
                            .addComponent(bilgiSoyIsimLbl))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yasBilgiLbl)
                            .addComponent(bilgiYasLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cinsiyetBilgiLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bilgiCinsiyetLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bilgiIsimLbl.setText(isim);
        bilgiSoyIsimLbl.setText(soyIsim);
        bilgiYasLbl.setText(yas);
        bilgiCinsiyetLbl.setText(cinsiyet);
        bilgiMedeniHalLbl.setText(medeniHal);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilgiFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilgiFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilgiFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilgiFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BilgiFormu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SoyIsimBilgiLbl;
    private javax.swing.JLabel bilgiCinsiyetLbl;
    private javax.swing.JLabel bilgiIsimLbl;
    private javax.swing.JLabel bilgiMedeniHalLbl;
    private javax.swing.JLabel bilgiSoyIsimLbl;
    private javax.swing.JLabel bilgiYasLbl;
    private javax.swing.JLabel cinsiyetBilgiLbl;
    private javax.swing.JLabel egitimLbl;
    private javax.swing.JLabel epostaBilgi;
    private javax.swing.JLabel epostaLbl;
    private javax.swing.JLabel iletisimBilgileriLbl;
    private javax.swing.JLabel isimBilgiLbl;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel kisiselBilgiLbl;
    private javax.swing.JLabel medeniHalBilgiLbl;
    private javax.swing.JLabel mezDerBilgi;
    private javax.swing.JLabel mezOkulBilgi;
    private javax.swing.JLabel mezOrtBilgi;
    private javax.swing.JLabel mezuniyetDereceBilgiLbl;
    private javax.swing.JLabel mezuniyetOkulBilgiLbl;
    private javax.swing.JLabel telBilgi;
    private javax.swing.JLabel telNoLbl;
    private javax.swing.JLabel yasBilgiLbl;
    // End of variables declaration//GEN-END:variables
}
