/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gelismisform;

/**
 *
 * @author ASUS PC
 */
public class EgitimBilgileriFormu extends javax.swing.JFrame {

     String mezuniyetDerecesi,mezunOlunanOkul,mezuniyetOrtalamasi,mezunOlunanBolum;

    public EgitimBilgileriFormu(String mezuniyetDerecesi, String mezunOlunanOkul,String mezunOlunanBolum ,String mezuniyetOrtalamasi) {
        initComponents();
        this.mezuniyetDerecesi = mezuniyetDerecesi;
        this.mezunOlunanOkul = mezunOlunanOkul;
        this.mezunOlunanBolum=mezunOlunanBolum;
        this.mezuniyetOrtalamasi = mezuniyetOrtalamasi;
    }
     
    public EgitimBilgileriFormu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        egitimBilgileriLbl = new javax.swing.JLabel();
        egitimMezuniyetDerLbl = new javax.swing.JLabel();
        egitimMezunOkulLbl = new javax.swing.JLabel();
        egitimMezunOrtLbl = new javax.swing.JLabel();
        egitimMezunDer_Lbl = new javax.swing.JLabel();
        egitimMezOkul_Lbl = new javax.swing.JLabel();
        egitimMezOrt_Lbl = new javax.swing.JLabel();
        egitimIlerleBtn = new javax.swing.JButton();
        egitimMezunBolumLbl = new javax.swing.JLabel();
        egitimMezBolum_Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        egitimBilgileriLbl.setText("              EĞİTİM BİLGİLERİ");

        egitimMezuniyetDerLbl.setText("Mezuniyet Derecesi");

        egitimMezunOkulLbl.setText("Mezun Olunan Okul");

        egitimMezunOrtLbl.setText("Mezuniyet Ortalaması");

        egitimMezunDer_Lbl.setText("Derece");

        egitimMezOkul_Lbl.setText("Okul");

        egitimMezOrt_Lbl.setText("Ortalama");

        egitimIlerleBtn.setText("İLERLE");
        egitimIlerleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egitimIlerleBtnActionPerformed(evt);
            }
        });

        egitimMezunBolumLbl.setText("Mezun Olunan Bölüm");

        egitimMezBolum_Lbl.setText("Bölüm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(egitimBilgileriLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(egitimMezuniyetDerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(egitimMezunOkulLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(egitimMezunOrtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(egitimMezunBolumLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egitimIlerleBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(egitimMezOrt_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(egitimMezBolum_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(egitimMezunDer_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(egitimMezOkul_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(egitimBilgileriLbl)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egitimMezuniyetDerLbl)
                    .addComponent(egitimMezunDer_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egitimMezunOkulLbl)
                    .addComponent(egitimMezOkul_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egitimMezOrt_Lbl)
                    .addComponent(egitimMezunOrtLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egitimMezunBolumLbl)
                    .addComponent(egitimMezBolum_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(egitimIlerleBtn)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        egitimMezunDer_Lbl.setText(mezuniyetDerecesi);
        egitimMezOkul_Lbl.setText(mezunOlunanOkul);
        egitimMezBolum_Lbl.setText(mezunOlunanBolum);
        egitimMezOrt_Lbl.setText(mezuniyetOrtalamasi);
    }//GEN-LAST:event_formWindowOpened

    private void egitimIlerleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egitimIlerleBtnActionPerformed
        IletisimBilgileri bilgiForm= new IletisimBilgileri();
        bilgiForm.setVisible(true);
    }//GEN-LAST:event_egitimIlerleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EgitimBilgileriFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EgitimBilgileriFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EgitimBilgileriFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EgitimBilgileriFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EgitimBilgileriFormu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel egitimBilgileriLbl;
    private javax.swing.JButton egitimIlerleBtn;
    private javax.swing.JLabel egitimMezBolum_Lbl;
    private javax.swing.JLabel egitimMezOkul_Lbl;
    private javax.swing.JLabel egitimMezOrt_Lbl;
    private javax.swing.JLabel egitimMezunBolumLbl;
    private javax.swing.JLabel egitimMezunDer_Lbl;
    private javax.swing.JLabel egitimMezunOkulLbl;
    private javax.swing.JLabel egitimMezunOrtLbl;
    private javax.swing.JLabel egitimMezuniyetDerLbl;
    // End of variables declaration//GEN-END:variables
}
