/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gelismisform;

/**
 *
 * @author ASUS PC
 */
public class KisiselBilgilerFormu extends javax.swing.JFrame {

    public String isim,soyIsim,yas,cinsiyet,medeniHal;

    public KisiselBilgilerFormu(String isim, String soyIsim, String yas, String cinsiyet, String medeniHal) {
        initComponents();
        this.isim = isim;
        this.soyIsim = soyIsim;
        this.yas = yas;
        this.cinsiyet = cinsiyet;
        this.medeniHal = medeniHal;
    }
    
    public KisiselBilgilerFormu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kisiselIsimLbl = new javax.swing.JLabel();
        kisiselSoyIsimLbl = new javax.swing.JLabel();
        kisiselYasLbl = new javax.swing.JLabel();
        kisiselCinsiyetLbl = new javax.swing.JLabel();
        kisiselMedeniHalLbl = new javax.swing.JLabel();
        kisiselIsim_Lbl = new javax.swing.JLabel();
        kisiselSoyIsim_Lbl = new javax.swing.JLabel();
        kisiselYas_Lbl = new javax.swing.JLabel();
        kisiselCinsiyet_Lbl = new javax.swing.JLabel();
        kisiselBilgilerFormuLbl = new javax.swing.JLabel();
        kisiselMedeniHal_Lbl = new javax.swing.JLabel();
        kisisel_IlerleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kisiselIsimLbl.setText("İSİM");

        kisiselSoyIsimLbl.setText("SOYİSİM");

        kisiselYasLbl.setText("YAŞ");

        kisiselCinsiyetLbl.setText("CİNSİYET");

        kisiselMedeniHalLbl.setText("MEDENİ HAL");

        kisiselIsim_Lbl.setText("isim");

        kisiselSoyIsim_Lbl.setText("soyIsim");

        kisiselYas_Lbl.setText("yas");

        kisiselCinsiyet_Lbl.setText("cinsiyet");

        kisiselBilgilerFormuLbl.setText("                KİŞİSEL BİLGİLER ");

        kisiselMedeniHal_Lbl.setText("medeniHal");

        kisisel_IlerleBtn.setText("İLERLE");
        kisisel_IlerleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisisel_IlerleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(kisiselBilgilerFormuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kisiselIsimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kisiselSoyIsimLbl)
                            .addComponent(kisiselYasLbl)
                            .addComponent(kisiselCinsiyetLbl)
                            .addComponent(kisiselMedeniHalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kisisel_IlerleBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kisiselIsim_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kisiselSoyIsim_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kisiselYas_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kisiselCinsiyet_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kisiselMedeniHal_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(kisiselBilgilerFormuLbl)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kisiselIsimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kisiselIsim_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kisiselSoyIsimLbl)
                    .addComponent(kisiselSoyIsim_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kisiselYasLbl)
                    .addComponent(kisiselYas_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kisiselCinsiyetLbl)
                    .addComponent(kisiselCinsiyet_Lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kisiselMedeniHalLbl)
                    .addComponent(kisiselMedeniHal_Lbl))
                .addGap(18, 18, 18)
                .addComponent(kisisel_IlerleBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        kisiselIsim_Lbl.setText(isim);
        kisiselSoyIsim_Lbl.setText(soyIsim);
        kisiselYas_Lbl.setText(yas);
        kisiselCinsiyet_Lbl.setText(cinsiyet);
        kisiselMedeniHal_Lbl.setText(medeniHal);
    }//GEN-LAST:event_formWindowOpened

    private void kisisel_IlerleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisisel_IlerleBtnActionPerformed
        EgitimBilgileri bilgiEgitim = new EgitimBilgileri();
        bilgiEgitim.setVisible(true);
    }//GEN-LAST:event_kisisel_IlerleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KisiselBilgilerFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KisiselBilgilerFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KisiselBilgilerFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KisiselBilgilerFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KisiselBilgilerFormu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel kisiselBilgilerFormuLbl;
    private javax.swing.JLabel kisiselCinsiyetLbl;
    private javax.swing.JLabel kisiselCinsiyet_Lbl;
    private javax.swing.JLabel kisiselIsimLbl;
    private javax.swing.JLabel kisiselIsim_Lbl;
    private javax.swing.JLabel kisiselMedeniHalLbl;
    private javax.swing.JLabel kisiselMedeniHal_Lbl;
    private javax.swing.JLabel kisiselSoyIsimLbl;
    private javax.swing.JLabel kisiselSoyIsim_Lbl;
    private javax.swing.JLabel kisiselYasLbl;
    private javax.swing.JLabel kisiselYas_Lbl;
    private javax.swing.JButton kisisel_IlerleBtn;
    // End of variables declaration//GEN-END:variables
}
